# Site settings
title: Artzoomi - разработка на Meteor, Node.js, Javascript, MongoDB сервисов для бизнеса и стартапов
email: hello@artzoomi.com
url: https://artzoomi.github.io
description: ""
skills: "Разработка стартапов и сервисов на Meteor, Node.js, Javascript, MongoDB - Создание современного дизайна"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Artzoomi
  location: Где мы
  social: Мы в соц.сетях
  credits: Контакты

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: vk
    url: https://vk.com/artzoomi
  - title: twitter
    url: https://twitter.com/artzoomi
  - title: facebook
    url: https://facebook.com/artzoomi

# Postal address (add as many lines as necessary)
address:
  - line: Россия, Мордовия, Саранск
  - line: ул. Коваленко, 20

# Credits content
credits: 'Email: hello@artzoomi.com, Тел.: +7 (964) 851-80-72'

# Build settings
markdown: kramdown
permalink: pretty
